name: password_generator
description: Generate and store your password only in your way.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  floor: ^1.3.0
  creator: ^0.3.3
  encrypt: ^5.0.1
  google_fonts: ^6.1.0
  clipboard: ^0.1.3
  package_info_plus: ^5.0.1
  webdav_client: ^1.1.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.3.2
  path: ^1.8.2
  crypto: ^3.0.2
  gbk_codec: ^0.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  go_router: ^12.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  floor_generator: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  go_router_builder: ^2.3.4
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
